#!/bin/sh
#PBS -l walltime=56:00:00,nodes=1:ppn=24,mem=62gb
#PBS -o /home/watkinse/qiuxx221/Result_files/Isoseq/out
#PBS -e /home/watkinse/qiuxx221/Result_files/Isoseq/error
#PBS -N trinity_TP5_de_novo
#PBS -M qiuxx221@umn.edu
#PBS -m abe
#PBS -r n

module load trinity/2.5.1
cd /home/watkinse/qiuxx221/Sequencing_reads/Fungicide_Project/FP5

Trinity --seqType fq --normalize_by_read_set \
--left WP5C_1_R1_clean.fastq,WP5C_2_R1_clean.fastq,WP5C_3_R1_clean.fastq,WP5S_1_R1_clean.fastq,WP5S_2_R1_clean.fastq,WP5S_3_R1_clean.fastq,FP5C_1_R1_clean.fastq,FP5C_2_R1_clean.fastq,FP5C_3_R1_clean.fastq,FP5S_1_R1_clean.fastq,FP5S_2_R1_clean.fastq,FP5S_3_R1_clean.fastq \
--right WP5C_1_R2_clean.fastq,WP5C_2_R2_clean.fastq,WP5C_3_R2_clean.fastq,WP5S_1_R2_clean.fastq,WP5S_2_R2_clean.fastq,WP5S_3_R2_clean.fastq,FP5C_1_R2_clean.fastq,FP5C_2_R2_clean.fastq,FP5C_3_R2_clean.fastq,FP5S_1_R2_clean.fastq,FP5S_2_R2_clean.fastq,FP5S_3_R2_clean.fastq \
--max_memory 62G --CPU 24 --normalize_reads --bflyCalculateCPU  --min_contig_length 200 \
--monitoring --output /scratch.global/qiu1010/TP5_de_novo_trinity
